# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37c0cf06f6be39d8d5c3c4c083d80c0885ae1ac328da5ba074b68cfbbe0231f532a986af4fae81a0f5b5c7fd011073ae7c44a652a091cb561c4ee0522876be20

test:
  secret_key_base: 83b2c2e44d4c7e59c78ddfd4d738ee4738f8cfcd01873d8266f96cf7bf76dd78ec63ea1724a592cc5117377b95c18d6766ee2cc4f49eca6d8ce441d4f282f6b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
